language: ruby
bundler_args: --without debug
script: "bundle exec rspec"
cache: bundler
rvm:
  - 2.1.3
sudo: false
addons:
  code_climate:
    repo_token: ca7f81d633af84944be40ec53434bc50b076fab7ea1db6d4108331ba0c0f1b94
env: CI=yes
